# conda env export -n absa --no-builds | findstr -v "^prefix: " > requirements.yml // on windows, replace findstr with grep for linux
# conda env create --file requirements.yml
# remove thundersvm, unless user has it installed: https://github.com/Xtra-Computing/thundersvm
name: absa
channels:
  - defaults
dependencies:
  - ca-certificates=2021.7.5
  - certifi=2021.5.30
  - openssl=1.1.1l
  - pip=21.0.1
  - python=3.8.11
  - setuptools=58.0.4
  - sqlite=3.36.0
  - vc=14.2
  - vs2015_runtime=14.27.29016
  - wheel=0.37.0
  - wincertstore=0.2
  - pip:
    - charset-normalizer==2.0.6
    - click==8.0.3
    - cloudpickle==2.0.0
    - colorama==0.4.4
    - cycler==0.10.0
    - emoji==1.6.0
    - et-xmlfile==1.1.0
    - future==0.18.2
    - hyperopt==0.2.5
    - idna==3.2
    - joblib==1.0.1
    - kiwisolver==1.3.2
    - matplotlib==3.4.3
    - networkx==2.6.3
    - nltk==3.6.5
    - numpy==1.21.2
    - openai==0.11.0
    - openpyxl==3.0.9
    - pandas==1.3.4
    - pandas-stubs==1.2.0.35
    - pillow==8.4.0
    - protobuf==3.18.1
    - psutil==5.8.0
    - pyparsing==2.4.7
    - python-dateutil==2.8.2
    - pytz==2021.3
    - regex==2021.10.23
    - requests==2.26.0
    - scikit-learn==1.0
    - scipy==1.7.1
    - six==1.16.0
    - sklearn==0.0
    - stanfordcorenlp==3.9.1.1
    - stanza==1.3.0
    - threadpoolctl==2.2.0
    - torch==1.9.1
    - tqdm==4.62.3
    - typing-extensions==3.10.0.2
    - urllib3==1.26.7
    - wordsegment==1.3.1